FROM centos

RUN yum update -y
RUN groupadd vmail -g 2222
RUN useradd vmail -r -g 2222 -u 2222 -d /var/vmail -m -c "mail user"
RUN yum remove -y exim sendmail
RUN yum install postfix cronie -y
RUN yum install vim -y
RUN cp /etc/postfix/main.cf{,.orig}
RUN echo -e "queue_directory = /var/spool/postfix
	command_directory = /usr/sbin
	daemon_directory = /usr/libexec/postfix
	data_directory = /var/lib/postfix
	mail_owner = postfix
	unknown_local_recipient_reject_code = 550
	alias_maps = hash:/etc/postfix/aliases
	alias_database = $alias_maps
	
	inet_interfaces = all
	inet_protocols = ipv4
	mydestination = $myhostname, localhost.$mydomain, localhost
	
	debug_peer_level = 2
	debugger_command =
	         PATH=/bin:/usr/bin:/usr/local/bin:/usr/X11R6/bin
	         ddd $daemon_directory/$process_name $process_id & sleep 5
	
	sendmail_path = /usr/sbin/sendmail.postfix
	newaliases_path = /usr/bin/newaliases.postfix
	mailq_path = /usr/bin/mailq.postfix
	setgid_group = postdrop
	html_directory = no
	manpage_directory = /usr/share/man
	sample_directory = /usr/share/doc/postfix-2.6.6/samples
	readme_directory = /usr/share/doc/postfix-2.6.6/README_FILES
	
	relay_domains = *
	virtual_alias_maps=hash:/etc/postfix/vmail_aliases
	virtual_mailbox_domains=hash:/etc/postfix/vmail_domains
	virtual_mailbox_maps=hash:/etc/postfix/vmail_mailbox
	
	virtual_mailbox_base = /var/vmail
	virtual_minimum_uid = 2222
	virtual_transport = virtual
	virtual_uid_maps = static:2222
	virtual_gid_maps = static:2222
	
	smtpd_sasl_auth_enable = yes
	smtpd_sasl_type = dovecot
	smtpd_sasl_path = /var/run/dovecot/auth-client
	smtpd_sasl_security_options = noanonymous
	smtpd_sasl_tls_security_options = $smtpd_sasl_security_options
	smtpd_sasl_local_domain = $mydomain
	broken_sasl_auth_clients = yes
	
	smtpd_recipient_restrictions = permit_mynetworks, permit_sasl_authenticated, reject_unauth_destination
        smtpd_relay_restrictions = permit_mynetworks, permit_sasl_authenticated, reject_unauth_destination" > /etc/postfix/main.cf

RUN echo -e " instances.cf OK " > /etc/postfix/vmail_domains
RUN echo -e " kapoor.abhishek@instances.cf instances.cf/kapoor.abhishek/ " > /etc/postfix/vmail_domains
RUN echo -e " kapoor.abhishek@instances.cf kapoor.abhishek@instances.cf
              root kapoor.abhishek@instances.cf " > /etc/postfix/vmail_aliases
RUN postmap /etc/postfix/vmail_domains
RUN postmap /etc/postfix/vmail_mailbox
RUN postmap /etc/postfix/vmail_aliases
RUN touch /etc/postfix/aliases
#RUN vim +/submission /etc/postfix/master.cf
RUN yum install -y dovecot
RUN cp /etc/dovecot/dovecot.conf{,.orig}
RUN echo -e " listen = *
ssl = no
protocols = imap lmtp
disable_plaintext_auth = no
auth_mechanisms = plain login
mail_access_groups = vmail
default_login_user = vmail
first_valid_uid = 2222
first_valid_gid = 2222
#mail_location = maildir:~/Maildir
mail_location = maildir:/var/vmail/%d/%n

passdb {
    driver = passwd-file
    args = scheme=SHA1 /etc/dovecot/passwd
}
userdb {
    driver = static
    args = uid=2222 gid=2222 home=/var/vmail/%d/%n allow_all_users=yes
}
service auth {
    unix_listener auth-client {
        group = postfix
        mode = 0660
        user = postfix
    }
    user = root
}
service imap-login {
  process_min_avail = 1
  user = vmail
}" > /etc/dovecot/dovecot.conf

RUN chkconfig postfix on
RUN chkconfig dovecot on
RUN service postfix restart
RUN service dovecot restart 


